// @generated Code generated by thrift-gen. Do not modify.

// Package keyvalue is generated code used to make or handle TChannel calls using Thrift.
package keyvalue

import (
	"fmt"

	athrift "github.com/apache/thrift/lib/go/thrift"
	"github.com/uber/tchannel-go/thrift"
)

// Interfaces for the service and client for the services defined in the IDL.

// TChanAdmin is the interface that defines the server handler and client interface.
type TChanAdmin interface {
	TChanBaseService

	ClearAll(ctx thrift.Context) error
}

// TChanKeyValue is the interface that defines the server handler and client interface.
type TChanKeyValue interface {
	TChanBaseService

	Get(ctx thrift.Context, key string) (string, error)
	Set(ctx thrift.Context, key string, value string) error
}

// TChanBaseService is the interface that defines the server handler and client interface.
type TChanBaseService interface {
	HealthCheck(ctx thrift.Context) (string, error)
}

// Implementation of a client and service handler.

type tchanAdminClient struct {
	TChanBaseService

	thriftService string
	client        thrift.TChanClient
}

func NewTChanAdminInheritedClient(thriftService string, client thrift.TChanClient) *tchanAdminClient {
	return &tchanAdminClient{
		NewTChanBaseServiceInheritedClient(thriftService, client),
		thriftService,
		client,
	}
}

// NewTChanAdminClient creates a client that can be used to make remote calls.
func NewTChanAdminClient(client thrift.TChanClient) TChanAdmin {
	return NewTChanAdminInheritedClient("Admin", client)
}

func (c *tchanAdminClient) ClearAll(ctx thrift.Context) error {
	var resp AdminClearAllResult
	args := AdminClearAllArgs{}
	success, err := c.client.Call(ctx, c.thriftService, "clearAll", &args, &resp)
	if err == nil && !success {
		if e := resp.NotAuthorized; e != nil {
			err = e
		}
	}

	return err
}

type tchanAdminServer struct {
	thrift.TChanServer

	handler TChanAdmin

	interceptorRunner thrift.InterceptorRunner
}

// NewTChanAdminServer wraps a handler for TChanAdmin so it can be
// registered with a thrift.Server.
func NewTChanAdminServer(handler TChanAdmin) thrift.TChanServer {
	return &tchanAdminServer{
		TChanServer: NewTChanBaseServiceServer(handler),
		handler:     handler,
	}
}

func (s *tchanAdminServer) Service() string {
	return "Admin"
}

func (s *tchanAdminServer) Methods() []string {
	return []string{
		"clearAll",

		"HealthCheck",
	}
}

// RegisterInterceptors registers the provided interceptors with the server.
func (s *tchanAdminServer) RegisterInterceptorRunner(runner thrift.InterceptorRunner) {
	s.interceptorRunner = runner
}

func (s *tchanAdminServer) Handle(ctx thrift.Context, methodName string, protocol athrift.TProtocol) (bool, athrift.TStruct, error) {
	switch methodName {
	case "clearAll":
		return s.handleClearAll(ctx, protocol)

	case "HealthCheck":
		return s.TChanServer.Handle(ctx, methodName, protocol)
	default:
		return false, nil, fmt.Errorf("method %v not found in service %v", methodName, s.Service())
	}
}

func (s *tchanAdminServer) handleClearAll(ctx thrift.Context, protocol athrift.TProtocol) (handled bool, resp athrift.TStruct, retErr error) {
	var req AdminClearAllArgs
	var res AdminClearAllResult
	const serviceMethod = "Admin::clearAll"

	if readErr := req.Read(protocol); readErr != nil {
		return false, nil, readErr
	}

	postRun, err := s.interceptorRunner.RunPre(ctx, serviceMethod, &req)

	defer func() {
		resp = &res
		retErr = postRun(resp, err)
		handled = retErr == nil
		if retErr != nil {
			resp = nil
			switch v := retErr.(type) {
			case *NotAuthorized:
				if v == nil {
					retErr = fmt.Errorf("Handler for notAuthorized returned non-nil error type *NotAuthorized but nil value")
				} else {
					res.NotAuthorized = v
					retErr = nil
					resp = &res
				}
			}
		}
	}()

	if err != nil {
		return
	}

	err =
		s.handler.ClearAll(ctx)

	return
}

type tchanKeyValueClient struct {
	TChanBaseService

	thriftService string
	client        thrift.TChanClient
}

func NewTChanKeyValueInheritedClient(thriftService string, client thrift.TChanClient) *tchanKeyValueClient {
	return &tchanKeyValueClient{
		NewTChanBaseServiceInheritedClient(thriftService, client),
		thriftService,
		client,
	}
}

// NewTChanKeyValueClient creates a client that can be used to make remote calls.
func NewTChanKeyValueClient(client thrift.TChanClient) TChanKeyValue {
	return NewTChanKeyValueInheritedClient("KeyValue", client)
}

func (c *tchanKeyValueClient) Get(ctx thrift.Context, key string) (string, error) {
	var resp KeyValueGetResult
	args := KeyValueGetArgs{
		Key: key,
	}
	success, err := c.client.Call(ctx, c.thriftService, "Get", &args, &resp)
	if err == nil && !success {
		if e := resp.NotFound; e != nil {
			err = e
		}
		if e := resp.InvalidKey; e != nil {
			err = e
		}
	}

	return resp.GetSuccess(), err
}

func (c *tchanKeyValueClient) Set(ctx thrift.Context, key string, value string) error {
	var resp KeyValueSetResult
	args := KeyValueSetArgs{
		Key:   key,
		Value: value,
	}
	success, err := c.client.Call(ctx, c.thriftService, "Set", &args, &resp)
	if err == nil && !success {
		if e := resp.InvalidKey; e != nil {
			err = e
		}
	}

	return err
}

type tchanKeyValueServer struct {
	thrift.TChanServer

	handler TChanKeyValue

	interceptorRunner thrift.InterceptorRunner
}

// NewTChanKeyValueServer wraps a handler for TChanKeyValue so it can be
// registered with a thrift.Server.
func NewTChanKeyValueServer(handler TChanKeyValue) thrift.TChanServer {
	return &tchanKeyValueServer{
		TChanServer: NewTChanBaseServiceServer(handler),
		handler:     handler,
	}
}

func (s *tchanKeyValueServer) Service() string {
	return "KeyValue"
}

func (s *tchanKeyValueServer) Methods() []string {
	return []string{
		"Get",
		"Set",

		"HealthCheck",
	}
}

// RegisterInterceptors registers the provided interceptors with the server.
func (s *tchanKeyValueServer) RegisterInterceptorRunner(runner thrift.InterceptorRunner) {
	s.interceptorRunner = runner
}

func (s *tchanKeyValueServer) Handle(ctx thrift.Context, methodName string, protocol athrift.TProtocol) (bool, athrift.TStruct, error) {
	switch methodName {
	case "Get":
		return s.handleGet(ctx, protocol)
	case "Set":
		return s.handleSet(ctx, protocol)

	case "HealthCheck":
		return s.TChanServer.Handle(ctx, methodName, protocol)
	default:
		return false, nil, fmt.Errorf("method %v not found in service %v", methodName, s.Service())
	}
}

func (s *tchanKeyValueServer) handleGet(ctx thrift.Context, protocol athrift.TProtocol) (handled bool, resp athrift.TStruct, retErr error) {
	var req KeyValueGetArgs
	var res KeyValueGetResult
	const serviceMethod = "KeyValue::Get"

	if readErr := req.Read(protocol); readErr != nil {
		return false, nil, readErr
	}

	postRun, err := s.interceptorRunner.RunPre(ctx, serviceMethod, &req)

	defer func() {
		resp = &res
		retErr = postRun(resp, err)
		handled = retErr == nil
		if retErr != nil {
			resp = nil
			switch v := retErr.(type) {
			case *KeyNotFound:
				if v == nil {
					retErr = fmt.Errorf("Handler for notFound returned non-nil error type *KeyNotFound but nil value")
				} else {
					res.NotFound = v
					retErr = nil
					resp = &res
				}
			case *InvalidKey:
				if v == nil {
					retErr = fmt.Errorf("Handler for invalidKey returned non-nil error type *InvalidKey but nil value")
				} else {
					res.InvalidKey = v
					retErr = nil
					resp = &res
				}
			}
		}
	}()

	if err != nil {
		return
	}

	r, err :=
		s.handler.Get(ctx, req.Key)

	if err == nil {
		res.Success = &r
	}

	return
}

func (s *tchanKeyValueServer) handleSet(ctx thrift.Context, protocol athrift.TProtocol) (handled bool, resp athrift.TStruct, retErr error) {
	var req KeyValueSetArgs
	var res KeyValueSetResult
	const serviceMethod = "KeyValue::Set"

	if readErr := req.Read(protocol); readErr != nil {
		return false, nil, readErr
	}

	postRun, err := s.interceptorRunner.RunPre(ctx, serviceMethod, &req)

	defer func() {
		resp = &res
		retErr = postRun(resp, err)
		handled = retErr == nil
		if retErr != nil {
			resp = nil
			switch v := retErr.(type) {
			case *InvalidKey:
				if v == nil {
					retErr = fmt.Errorf("Handler for invalidKey returned non-nil error type *InvalidKey but nil value")
				} else {
					res.InvalidKey = v
					retErr = nil
					resp = &res
				}
			}
		}
	}()

	if err != nil {
		return
	}

	err =
		s.handler.Set(ctx, req.Key, req.Value)

	return
}

type tchanBaseServiceClient struct {
	thriftService string
	client        thrift.TChanClient
}

func NewTChanBaseServiceInheritedClient(thriftService string, client thrift.TChanClient) *tchanBaseServiceClient {
	return &tchanBaseServiceClient{
		thriftService,
		client,
	}
}

// NewTChanBaseServiceClient creates a client that can be used to make remote calls.
func NewTChanBaseServiceClient(client thrift.TChanClient) TChanBaseService {
	return NewTChanBaseServiceInheritedClient("baseService", client)
}

func (c *tchanBaseServiceClient) HealthCheck(ctx thrift.Context) (string, error) {
	var resp BaseServiceHealthCheckResult
	args := BaseServiceHealthCheckArgs{}
	success, err := c.client.Call(ctx, c.thriftService, "HealthCheck", &args, &resp)
	if err == nil && !success {
	}

	return resp.GetSuccess(), err
}

type tchanBaseServiceServer struct {
	handler TChanBaseService

	interceptorRunner thrift.InterceptorRunner
}

// NewTChanBaseServiceServer wraps a handler for TChanBaseService so it can be
// registered with a thrift.Server.
func NewTChanBaseServiceServer(handler TChanBaseService) thrift.TChanServer {
	return &tchanBaseServiceServer{
		handler: handler,
	}
}

func (s *tchanBaseServiceServer) Service() string {
	return "baseService"
}

func (s *tchanBaseServiceServer) Methods() []string {
	return []string{
		"HealthCheck",
	}
}

// RegisterInterceptors registers the provided interceptors with the server.
func (s *tchanBaseServiceServer) RegisterInterceptorRunner(runner thrift.InterceptorRunner) {
	s.interceptorRunner = runner
}

func (s *tchanBaseServiceServer) Handle(ctx thrift.Context, methodName string, protocol athrift.TProtocol) (bool, athrift.TStruct, error) {
	switch methodName {
	case "HealthCheck":
		return s.handleHealthCheck(ctx, protocol)

	default:
		return false, nil, fmt.Errorf("method %v not found in service %v", methodName, s.Service())
	}
}

func (s *tchanBaseServiceServer) handleHealthCheck(ctx thrift.Context, protocol athrift.TProtocol) (handled bool, resp athrift.TStruct, retErr error) {
	var req BaseServiceHealthCheckArgs
	var res BaseServiceHealthCheckResult
	const serviceMethod = "baseService::HealthCheck"

	if readErr := req.Read(protocol); readErr != nil {
		return false, nil, readErr
	}

	postRun, err := s.interceptorRunner.RunPre(ctx, serviceMethod, &req)

	defer func() {
		resp = &res
		retErr = postRun(resp, err)
		handled = retErr == nil
		if retErr != nil {
			resp = nil
		}
	}()

	if err != nil {
		return
	}

	r, err :=
		s.handler.HealthCheck(ctx)

	if err == nil {
		res.Success = &r
	}

	return
}
